## Numpy

* ### Numpy是一套處理多維陣列的工具函式
* ### Numpy提供數學與邏輯陣列運算
* ### Numpy提供傅立葉轉換函式
* ### NumPy提供線性代數、統計等內建函式

## ndarray

* ### Numpy 是一個 N-dimensional 陣列型態物件，ndarray
* ### 每個陣列元件必須有相同大小
* ### 每個陣列元件必須有相同資料類型
* ### 每個元件都具有資料類型物件

## 建構

### numpy.array(object, dtype=None, copy=True, order=None, subok= False, ndmin= 0 )

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
import numpy as np
a = np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [7]:
import numpy as np
a = np.array([1,2,3], dtype=complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


## Data Type

* ### bool
* ### int_
* ### intc
* ### intp
* ### int8
* ### int16
* ### int32
* ### int64
* ### float
* ### float16
* ### float32
* ### float64
* ### complex_
* ### complex64
* ### complex128

## 陣列屬性
### 陣列維度 - ndarray.shape

In [9]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


### 維度數目 - ndarray.ndim

In [12]:
import numpy as np 
a = np.arange(24) 
a.ndim 

1

In [13]:
b = a.reshape(2,4,3) 
print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


### 陣列元素大小 - numpy.itemsize

In [15]:
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


### 空陣列

In [17]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

[[1 2]
 [3 4]
 [5 6]]


### 1陣列

In [25]:
import numpy as np 
x = np.ones(5) 
print(x)

[ 1.  1.  1.  1.  1.]


In [27]:
import numpy as np 
x = np.ones([2,2], dtype=int) 
print(x)

[[1 1]
 [1 1]]


### 0陣列

In [20]:
import numpy as np 
x = np.zeros(5) 
print(x)

[ 0.  0.  0.  0.  0.]


In [24]:
import numpy as np 
x = np.zeros((2,3), dtype=int) 
print(x)

[[0 0 0]
 [0 0 0]]


### numpy.asarray

In [28]:
x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [30]:
x = (1,2,3) 
a = np.asarray(x,dtype=float) 
print(a)

[ 1.  2.  3.]


In [33]:
import numpy as np 
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

[(1, 2, 3) (4, 5)]


### numpy.arange
**numpy.arange(start, end, step, dtype)**

In [34]:
import numpy as np 
x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [35]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
print(x)

[ 0.  1.  2.  3.  4.]


### numpy.linspace
**numpy.linspace(start, end, num, endpoint, retstep, dtype)**

In [36]:
import numpy as np 
x = np.linspace(10,20,5) 
print(x)

[ 10.   12.5  15.   17.5  20. ]


In [37]:
import numpy as np 
x = np.linspace(10,20,5, endpoint=False) 
print(x)

[ 10.  12.  14.  16.  18.]


### Array slicing and Indexing