# <center>Numpy學習筆記</center>
## 目錄
1. [Numpy簡介](#Numpy-簡介)
2. [Python基本資料型別](#Python基本資料型別)
3. [Numpy數列](#Numpy數列)
4. [定義陣列](#定義陣列)
4. [Numpy資料型別](#Numpy資料型別)
5. [數列資料索引與分割](#數列資料索引與分割)
3. [特殊矩陣](#特殊矩陣)
5. [Numpy陣列運算](#Numpy陣列運算)
2. [numpy讀取檔案資料](#numpy讀取檔案資料)
1. [Numpy統計函數](#Numpy統計函數)

**Chapter 2 Introduction to NumPy**
* Understanding Data Types in Python
* The Basics of NumPy Arrays
* Computation on NumPy Arrays: Universal Functions
* Aggregations: Min, Max, and Everything in Between
* Computation on Arrays: Broadcasting
* Comparisons, Masks, and Boolean Logic
* Fancy Indexing
* Sorting Arrays
* Structured Data: NumPy’s Structured Arrays

### Numpy 簡介


1. NumPy是Python語言的一個擴充程式庫。支援大量的**高維度陣列與矩陣運算**，此外也提供陣列運算的數學函式庫。NumPy為**開放原始碼**並且由許多協作者共同維護開發。

2. NumPy引入了多維陣列以及可以直接有效率地操作多維陣列的函式與運算子。因此在NumPy上只要能被表示為針對陣列或矩陣運算的演算法，其執行效率幾乎都可以與編譯過的等效C語言程式碼一樣快。

3. NumPy可以結合其它的Python擴充函式庫。例如**SciPy函式庫**提供了許多與MATLAB相似的功能；及**Matplotlib函式庫**，與MATLAB內建繪圖功能類似的函式庫。

4. NumPy的核心功能是**ndarray**（即n-dimensional array，多維陣列）資料結構。一個表示多維度、同質並且固定大小的陣列物件。


---------------------

### Python基本資料型別

Python可以處理數值與文字資料。Python所能處理的數值資料型別包括「整數」、「浮點數」、「複數」、及「布林數」。不同資料型別佔據記憶體大小決定資料範圍。
* 整數(int)，如1, 23, 789
* 浮點數(float)，如12.3, 1.23e10
* 複數(complex)，如1+2j
* 布林數(boolean)，如True或 False

#### 整數(Integer)

在Python中，只要沒有帶小數點的數值或負數，都視為整數，且整數的大小是沒有限制的，例如

In [1]:
1000000000000000000000000000000000000000000000000000000+1

1000000000000000000000000000000000000000000000000000001

#### 浮點數(float)

浮點數是帶有小數點的數值，如12.345，0.87654，也可以使用科學符號表示，如1.234e5，0.00345e10。

In [2]:
print(1.23, type(1.23))
print(0.00543e5,  type(1.23))

1.23 <class 'float'>
543.0 <class 'float'>


* 內建函數type()可以用來顯示資料的型別
* 0.00543e5 = 0.00543 x 10<sup>**5**</sup> = 5.43 x 10<sup>**2**</sup> = 543.0

#### 複數(complex)

帶有虛數的數，如 1+2j

#### 布林值(Boolean value)

布林值包含「真」與「假」二個值，真假值是有邏輯判斷式來決定，邏輯式有關於一個事實(Fact)的真假，例如 (5>3) 是一個事實，如果 5>3 為真，則布林值為True，否則布林值為False。

In [4]:
print(5>3, type(5>3)) # 5>3為真
print(0==5, type(0==5)) # 0 == 5 為假

True <class 'bool'>
False <class 'bool'>


### Numpy數列

#### Pyhton List與numpy array記憶體大小比較

>* Python List所占記憶體包含(1)List資訊記憶體、(2)指向元素所需的記憶體、及(3)List元素所需的記憶體
>*  numpy array所占記憶體包含(1)numpy array物件所佔記憶體，及(2)numpy array元素所需的記憶體

1. **python list 記憶體需求分析**

    a. ListList物件及指向元素記憶體需求 (64 + 8 * 元素數量) <br>
    b. List元素所需記憶體 (元素型別記憶體需求 * 元素數量)
    
    List所需的記憶體 = a + b


In [16]:
from sys import getsizeof
lst = [1, 2, 3]
size_of_list_object = getsizeof(lst)
size_of_list_elements = getsizeof(lst[0])*len(lst)
print("List物件及指向元素記憶體需求： ", getsizeof(lst))
print("List元素所需記憶體[1, 2, 3]： ", size_of_list_elements)
print("List(lst)記憶體總共需求：", size_of_list_object+size_of_list_elements)
print("空List所佔記憶體：", getsizeof([]))


List物件及指向元素記憶體需求：  88
List元素所需記憶體[1, 2,3]：  84
List(lst)記憶體總共需求： 172
空List所佔記憶體： 64


2. **numpy array 記憶體需求分析**

    a. 空numpy array記憶體需求<br>
    b. numpy array 元素記憶體需求(元素型別記憶體需求 * 元素數量)
    
    numpy array 所需的記憶體 = a + b

In [19]:
from sys import getsizeof
import numpy as np
a = np.array([1, 3, 4])
e = np.array([])
print("空numpy array記憶體需求：", getsizeof(e)) #96
print("具3個整數的numpy array記憶體需求： ", getsizeof(a)) #108
print("每一個元素所需記憶體：", (getsizeof(a)-getsizeof(e))/3) #np.int32

空numpy array記憶體需求： 96
具3個整數的numpy array記憶體需求：  108
每一個元素所需記憶體： 4.0


#### Python List與 numpy array執行速度比較

In [35]:
import time
size_of_vec = 1000000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [53]:
t1 = pure_python_version()
t2 = numpy_version()
print("{0:>30s} {1:10.7f} ".format("execution time of pure python",t1))
print("{0:>30s} {1:10.7f} ".format("executrion time of numpy array",t2))
print("numpy array 比 python List 快 {:5.2f} 倍".format(t1/t2))

 execution time of pure python  0.3343043 
executrion time of numpy array  0.0050046 
numpy array 比 python List 快 66.80 倍


### 定義陣列

numpy 提供一個 **`arange`**方法用來將數值範圍產生等距數列，方法定義如後 **`np.arange([start,] stop[, step], [, dtype=None])`**
* a = `np.arange(1, 10)` 結果 a = \[1 2 3 4 5 6 7 8 9\]
* a = `np.arange(10.4)` 結果 a = \[0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10.\]
* a = `np.arange(0.5, 10.4, 0.8)` 結果 a = \[0.5 1.3 2.1 2.9 3.7 4.5 5.3 6.1 6.9 7.7 8.5 9.3 10.1\]
* a = `np.arange(0.5, 10.4, 0.8, int)` 結果 a = \[0 1 2 2 3 4 5 6 6 7 8 9 10 11 12\]

In [54]:
import numpy as np
a = np.arange(1, 10); print(a)
a = np.arange(10.4); print(a)
a = np.arange(0.5, 10.4, 0.8); print(a)
a = np.arange(0.5, 10.4, 0.8, int); print(a)

[1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


另一個numpy方法`linspce`可以用來將數值範圍分隔成**num**個區間的數列，方法定義如後**`linsapce(start, stop, num=50, endpoint=True, retstep=False)`**，如果**endpoint=True**，**stop端點數值**必須包含於產生的數列。如果num沒有指定，則預設值為**50**。endpoint的預設值為**True**。retstep=**True**則傳回分割值。

In [64]:
a = np.linspace(1, 10, 5)
print(a)
a = np.linspace(1, 10, 5, endpoint=False)
print(a)
a = np.linspace(1, 10)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]
[1.  2.8 4.6 6.4 8.2]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [69]:
samples, spacing = np.linspace(1, 10, 20, retstep=True)
print(spacing)
samples, spacing = np.linspace(1, 10, 20, endpoint=False, retstep=True)
print(spacing)

0.47368421052631576
0.45


針對一個純量數值(如123)，有別於是數列，則其維度為0。從向量空間的觀點而言，有一維空間(1-d space)，二維空間(2-d space)，及三維空間(3-d space)，一維空間的維度為1，而純數值的維度為0。numpy的`np.ndim()`用來獲得數列的維度，另numpy array的屬性**`ndim`**也可用於獲得數列的維度。

In [83]:
import numpy as np
x = np.array(42)
print("x = ", x)
print("x的型別 =  ", type(x)) #注意此處x的型別並非為整數，而是numpy數列
print("x的維度 = ", np.ndim(x))

x =  42
x的型別 =   <class 'numpy.ndarray'>
x的維度 =  0


利用`np.linspace(1, 10)`建立一個數列，`np.ndim()`方法可用來檢查數列的維度。

In [74]:
a = np.linspace(1, 10)
print("a 的維度 ", np.ndim(a))

a 的維度  1


numpy提供`np.array()`方法用來將python List轉換為numpy array，如`np.array([1, 2, 3])`將`[1, 2, 3]`轉換為一維數列`[1 2 3]`，`np.array([[1, 0],[0,1]]`將轉換成一個二維陣列，\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}

In [79]:
# one dimensional array
a = np.array([1, 2, 3])
print("a = ", a)
print("a的型別為", type(a))
print("a的維度 = ", np.ndim(a))

a =  [1 2 3]
a的型別為 <class 'numpy.ndarray'>
a的維度 =  1


In [81]:
# two dimensional array
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a = ", a)
print("a的型別為", type(a))
print("a的維度 = ", np.ndim(a))

a =  [[1 2 3]
 [4 5 6]]
a的型別為 <class 'numpy.ndarray'>
a的維度 =  2


In [87]:
# three dimensional array
a = np.array([ [[111, 112, 113], [121, 122, 123], [131, 132, 133]],
              [[211, 212, 213], [221, 222, 223], [231, 232, 233]],
               [[311, 312, 313], [321, 322, 323], [331, 332, 333]] ])
print("a = ", a)
print("a的型別為", type(a))
print("a的維度 = ", np.ndim(a))

a =  [[[111 112 113]
  [121 122 123]
  [131 132 133]]

 [[211 212 213]
  [221 222 223]
  [231 232 233]]

 [[311 312 313]
  [321 322 323]
  [331 332 333]]]
a的型別為 <class 'numpy.ndarray'>
a的維度 =  3


![](pic/matrix3d.png)

#### 改變陣列形狀
numpy提供**`np.shape()`**方法及**`.shape`**屬性用於獲得陣列的形狀資訊，如a.shape為(3, 3, 3)，表示a為一個3x3x3的立方矩陣。

陣列的方法`.reshape()`可以用來改變陣列的列維度與行維度，以致於改變陣列形狀。

In [90]:
print(np.shape(a))
print(a.shape)

(3, 3, 3)
(3, 3, 3)


#### Numpy資料型別

numpy的資料型別比python程式語言所定義的資料型別豐富，詳細的numpy的資料型別可以參考SciPy.org中numpy.dtype網頁。numpy的`np.dtype()`函數來定義資料的型別，如定義純量資料型別`np.dtype(np.int16)`，或是可以定義資料表中謀一個欄位的資料型別，如`np.dtype([('f1', np.int16)])`定義資料表f1欄位的資料型別為`int16`。numpy的數值資料型別的範圍如下表

| 數值型別 |  墅值範圍   |
|:---------------:|:---------------------|
| np.int8       |  Byte(-128 to 127) |
| np.int16    | Integer(-32768 to 32767) |
| np.int32    | Integer (-2147483648 to 2147483647) |
| np.int64    | Integer (-9223372036854775808 to 9223372036854775807)|


numpy的數值資料型別為長度固定，因此當數值超過所能處理的數值範圍時，可能產生**溢位錯誤(overflow errors)**。參考下例，100<sup>8</sup>在`np.int64`中可以處理，但是如果數值型別設定為`np.int32`時可能發生錯誤。

In [2]:
import numpy as np
np.power(100, 8, dtype=np.int64)

10000000000000000

In [4]:
import numpy as np
np.power(100, 8, dtype=np.int32)

1874919424

### 數列資料索引與分割

#### 定位資料

從一個數列資料中可以根據資料位置(索引、地址)快速存取資料，例如一個數列資料 a = `[1 2 2 4 5 6 9 7 7]`，`a[3]`可以快速找到數列中第4筆資料4。 數列索引的規則與Pyhotn List相同，第一筆資料的索引值為0。

In [35]:
import numpy as np
a = np.array([1, 2, 2, 4, 5, 6, 9, 7, 7])
print("a數列的第1筆資料為",a[0])
print("a數列的第3筆資料為",a[2])
print("a數列的第5筆資料為",a[4])

a數列的第1筆資料為 1
a數列的第3筆資料為 2
a數列的第5筆資料為 5


對於二維陣列資料的資料索引方式，必須指定「列」與「行」的參考座標，如`m[3][2]`代表m陣列中第4列，第3行的資料值。也可使用`m[3,2]`的索引方式讀取資料。

In [43]:
import numpy as np
m = np.array([[1, 2, 3, 9],
            [4, 5, 6, 8],
            [7, 8, 9, 7],
             [11, 12, 13, 15]])
print("陣列a的維度= ", m.shape)
print(m[3][2])
print(m[3,2])

陣列a的維度=  (4, 4)
13
13


如果索引資料的參考坐標超出範圍將會產生 `Index Error: out of bounds`的錯誤，如m陣列只有4列，`m[4,1]`存取第5列資料，因此發生超出範圍的索引錯誤。

In [42]:
print(m[4,1])

IndexError: index 4 is out of bounds for axis 0 with size 4

#### 分割資料

Numpy允許存取部分的陣列，如 `a = [0 1 2 3 4 5 6 7 8 9]`，`a[3:6]` 可獲得 `[3 4 5]`的a數列的部份。參考下例中的分割方式及結果。

In [45]:
import numpy as np
a = np.arange(10)
print(a, a.shape)
print(a[2:5]) #存取2-4(5-1)的資料
print(a[:4])  #存取0-3(4-1)的資料
print(a[6:])  #存取6-9(6-9)的資料
print(a[:])  #存取所有資料

[0 1 2 3 4 5 6 7 8 9] (10,)
[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


二維陣列資料的分割，二維陣列資料如下

\begin{bmatrix}
11&12&13&14&15\\
21&22&23&24&25\\
31&32&33&34&35\\
41&42&43&44&45\\
51&52&53&54&55
\end{bmatrix}

In [46]:
import numpy as np
a = np.array([
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45],
    [51,52,53,54,55]
])

In [47]:
print(a[:3, 2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [48]:
print(a[3:, :])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [49]:
print(a[:, 4:])

[[15]
 [25]
 [35]
 [45]
 [55]]


先以`np.arange(28)`建立`[0 1 2 3 ... 26 27]`的一維數列，再利用`.reshape(m, n)`重塑mxn的陣列。

In [53]:
import numpy as np
a = np.arange(40).reshape(5,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [54]:
print(a[::2, ::3])

[[ 0  3  6]
 [16 19 22]
 [32 35 38]]


In [55]:
print(a[::, ::3])

[[ 0  3  6]
 [ 8 11 14]
 [16 19 22]
 [24 27 30]
 [32 35 38]]


#### 陣列參考與拷貝

在numpy中 _陣列分割_ 只是建立一個**參考範圍**，稱之為「**view**」，並無影響記憶體的存取，`np.may_share_memory(a, b)`可用來檢查二個陣列是否使用同一塊記憶體。

In [2]:
import numpy as np
a = np.arange(10)
b = a[::2]
print(a)
print(b)
print(np.may_share_memory(a, b)) #表示a, b數列使用同一記憶體

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True


numpy提供陣列拷貝的函數，`np.copy(array)`。`a = np.array([1, 2, 3])`，b = `np.copy(a)`

In [6]:
import numpy as np
a = np.arange(10)
b = np.copy(a)
print(np.may_share_memory(a, b)) #表示a, b數列不是同一記憶體
b[0] = 99
print(a)
print(b) #b[0]的內容改變時，a陣列內容並未更動

False
[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


### 特殊矩陣

* ones(t, dtype)
* zeros(t, dtype)
* itentity(n, dtype)
* eye(n, m, k, dtype)

In [58]:
import numpy as np

m = np.ones((3,2))
print(m)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [60]:
import numpy as np

m = np.zeros((3,3))
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:
import numpy as np

m = np.identity(5)
print(m)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [64]:
import numpy as np

m = np.eye(4, 5, 2, dtype=np.int16)
print(m)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


### Numpy陣列運算

#### 純量數值與數列

一個純量數值與數列的算術運算(加、減、乘、除)

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
p = 2.5 + a
s = 2.5 - a
m = 2.5*a
d = 2.5/a
print(a)
print(p)
print(s)
print(m)
print(d)

#### 二數列運算

二數列的算術運算是二數列相對應位置的數值運算。相當於 `array(a[i]+b[i], i = 1 to len(a))`

In [7]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 9])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[1 2 3 4 5]
[2 4 6 8 9]
[ 3  6  9 12 14]
[-1 -2 -3 -4 -4]
[ 2  8 18 32 45]
[0.5        0.5        0.5        0.5        0.55555556]


二個矩陣算術運算，如

a = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}

b =  \begin{bmatrix} 4 & 3 \\ 2 & 1 \end{bmatrix}

* a + b = ?
* a - b = ?
* a * b = ?
* a / b = ?

In [13]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[4, 3],[2, 1]])
print('a=', a)
print('b=', b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

a= [[1 2]
 [3 4]]
b= [[4 3]
 [2 1]]
[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]
[[4 6]
 [6 4]]
[[0.25       0.66666667]
 [1.5        4.        ]]


#### 矩陣運算

* **向量運算**

二個項量可以進行向量加法、減法、及利用向量內積求二個向量的夾角，如下圖所示

![](pic/vectorpic.png)

In [17]:
import numpy as np
a = np.array([3,2])
b = np.array([5,1])
print("a + b = ", a+b)
print("a - b = ", a-b)

a + b =  [8 3]
a - b =  [-2  1]


numpy提供`np.dot(a, b, out=None)`向量內積函數，a和b是二個向量

In [24]:
import numpy as np
a = np.array([3,2])
b = np.array([5,1])
d = np.dot(a,b)
print(d) #3*5+2*1=17

17


* **計算向量夾角**

In [31]:
import numpy as np
a = np.array([3,2])
b = np.array([5,1])
d = np.dot(a,b)
print('a, b內積= ',d) #3*5+2*1=17
x_modulus = np.sqrt((a*a).sum())
y_modulus = np.sqrt((b*b).sum())
print('a向量長度= ',x_modulus)
print('b向量長度= ',y_modulus)
cos_angle = d/x_modulus/y_modulus
angle = np.arccos(cos_angle)
print('a,b夾角= ',angle)
print('a,b夾角= ',angle*360/2/np.pi)

a, b內積=  17
a向量長度=  3.605551275463989
b向量長度=  5.0990195135927845
a,b夾角=  0.3906070436976867
a,b夾角=  22.38013505195957


* **矩陣相乘**

![matrix multiply](./pic/matrixmp.png)

In [65]:
x = np.matrix([[2,3],[3,5]])
print(x)
y = np.matrix([[1,2],[5,-1]])
print(y)
print(x*y) #[[2*1+3*5, 2*2+3*-1],[3*1+5*5, 3*2+5*-1]]

[[2 3]
 [3 5]]
[[ 1  2]
 [ 5 -1]]
[[17  1]
 [28  1]]


### numpy讀取檔案資料

對於大量數值資料輸入，檔案室不錯的選擇。numpy可以經由`np.loadtxt(file, delimiter="", skiprows=n, usecols=[...])`讀區檔案中的數值資料，讀取檔案的格式可以是`.txt`或`.csv`檔案。如果一個檔案的內容如下，檔案名稱為`abc.txt`。

11<br>
12<br>
13<br>
14<br>
.....<br>
18<br>
19<br>
20

In [13]:
import numpy as np
narray = np.loadtxt("data/abc.txt")
print(type(narray))
print(narray)
print(narray.ndim)
print(narray.shape)

<class 'numpy.ndarray'>
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
1
(10,)


對一個`.csv`檔案，可以`np.loadtxt(file, delimiter=",")`來讀取檔案中的數值資料。檔案`xyz.csv`的內容如下

11, 12, 13, 14, 15, 16, 17, 18, 19, 20<br>
21, 22, 23, 24, 25, 26, 27, 28, 29, 30

In [16]:
import numpy as np
narray = np.loadtxt("data/xyz.csv", delimiter=",", usecols=[1,3,5])
print(type(narray))
print(narray)
print(narray.ndim)
print(narray.shape)

<class 'numpy.ndarray'>
[[12. 14. 16.]
 [22. 24. 26.]]
2
(2, 3)


如果一個檔案的內容如下，檔案名稱為`xyz1.csv`，可以利用`np.loadtxt(xyz1.csv, delimiter=",", skiprows=1)`來讀取檔案中的數值資料。

以下為數列<br>
11, 12, 13, 14, 15, 16, 17, 18, 19, 20<br>
21, 22, 23, 24, 25, 26, 27, 28, 29, 30

In [28]:
import numpy as np
import codecs
filecp = codecs.open("data/xyz1.csv", encoding = 'utf-8')
narray = np.loadtxt(filecp, delimiter=",", skiprows=1, usecols=[2,4,6,8])
print(type(narray))
print(narray)
print(narray.ndim)
print(narray.shape)

<class 'numpy.ndarray'>
[[13. 15. 17. 19.]
 [23. 25. 27. 29.]]
2
(2, 4)


上例讀取檔案中資料時，由於第一行為中文說明，讀取資料時欲跳過該行，因此`skiprows`的參數設定為1，但讀取過程中發現編碼錯誤的訊息，<span style = "color:red;font-weight:bold;">UnicodeDecodeError: 'cp950' codec can't decode byte 0xb8 in position 4: illegal multibyte sequence</span>，利用編碼處理的套件**`import codecs`**先執行**`filecp = codecs.open("data/xyz1.csv", encoding = 'utf-8')`**，則可順利讀取資料。`usecols`參數在設定所要讀取的行。

### Numpy統計函數

numpy提供下列的統計函數


| 統計函數         |     函數功能     |
|:--------------------:|:---------------------|
|np.max()                 |    最大值           |
|np.min()                 |    最小值           |
|np.median()                 |    中值          |
|np.mean()                 |    平均值           |
|np.var()                 |    差異數           |
|np.std()                 |    標準差           |
|np.percentile()                 |        百分位數       |
|np.sort()                 |      數值排序       |

In [66]:
import numpy as np
narray = np.arange(20)
print(np.max(narray))
print(np.min(narray))
print(np.median(narray))
print(np.mean(narray))
print(np.var(narray))
print(np.std(narray))
print(np.percentile(narray,[ 2.5, 97.5]))

19
0
9.5
9.5
33.25
5.766281297335398
[ 0.475 18.525]


In [61]:
r = np.random.permutation(narray)
print(r)

[[13. 15. 17. 19.]
 [23. 25. 27. 29.]]


In [63]:
print(narray)
np.random.shuffle(narray)
print(narray)

[[23. 25. 27. 29.]
 [13. 15. 17. 19.]]
[[23. 25. 27. 29.]
 [13. 15. 17. 19.]]
